version: '3.7'
services:
    database:
        container_name: 'database'
        image: postgres
        ports:
          - '5432:5432'
        restart: always
        environment:
          POSTGRES_PASSWORD: pass
        #volumes:
        #    - ./postgres-data:/var/lib/postgresql/data
        networks:
          - app-health-network
    app:
        container_name: 'app-health-app'
        image: 'app-health-app'
        volumes:
           - "/etc/timezone:/etc/timezone:ro"
           - "/etc/localtime:/etc/localtime:ro"
        build:
            context: .
            dockerfile: Dockerfile-app
        depends_on:
           - 'database'
        ports:
           - '5000:5000'
        networks:
           - app-health-network 
        
    workerservice:
        container_name: 'health-check-ws'
        image: 'health-check-ws'
        volumes:
           - "/etc/timezone:/etc/timezone:ro"
           - "/etc/localtime:/etc/localtime:ro"
        build:
          context: .
          dockerfile: Dockerfile-ws
        depends_on:
           - 'database'
        networks:
           - app-health-network    
networks:
  app-health-network:
    driver: bridge
