FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src

COPY ApplicationHealth/MvcWebUI/*.csproj ApplicationHealth/MvcWebUI/
COPY ApplicationHealth/Services/*.csproj ApplicationHealth/Services/
COPY ApplicationHealth/Domain/*.csproj ApplicationHealth/Domain/
COPY ApplicationHealth/Infrastructure/*.csproj ApplicationHealth/Infrastructure/

COPY Shared/Shared.Domain/*.csproj Shared/Shared.Domain/
COPY Shared/Shared.Infrastructure/*.csproj Shared/Shared.Infrastructure/

RUN dotnet restore ApplicationHealth/MvcWebUI/ApplicationHealth.MvcWebUI.csproj

COPY . .
WORKDIR "/src/ApplicationHealth/MvcWebUI"
RUN dotnet build "ApplicationHealth.MvcWebUI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ApplicationHealth.MvcWebUI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ApplicationHealth.MvcWebUI.dll", "--urls", "http://*:5000;http://*:5001"]
